"use client"

import { Report } from "@/lib/types"
import { Header } from "@/components/layout/header"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { Download, Printer } from "lucide-react"
import { ExecutiveSnapshot } from "./sections/executive-snapshot"
import { AQVBreakdown } from "./sections/aqv-breakdown"
import { MonetizationPotential } from "./sections/monetization-potential"
import { PeerBenchmarking } from "./sections/peer-benchmarking"
import { ActionableRecommendations } from "./sections/actionable-recommendations"
import { MethodologyAppendix } from "./sections/methodology-appendix"

interface ReportViewProps {
  report: Report
}

export function ReportView({ report }: ReportViewProps) {
  const handlePrint = () => {
    window.print()
  }

  const handleDownloadPDF = async () => {
    // For PDF export, we'll use the browser's print functionality
    // In production, this could call a Puppeteer/Playwright API endpoint
    window.print()
  }

  return (
    <div className="min-h-screen bg-white">
      {/* Header - hidden in print */}
      <div className="no-print">
        <Header />
        <div className="container py-4 flex items-center justify-between border-b">
          <div>
            <h1 className="text-lg font-semibold">{report.creator.name}</h1>
            <p className="text-sm text-muted-foreground">
              {report.creator.handle} • {report.creator.platform} • {report.creator.category}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={handlePrint} className="gap-2">
              <Printer className="h-4 w-4" />
              Print
            </Button>
            <Button size="sm" onClick={handleDownloadPDF} className="gap-2">
              <Download className="h-4 w-4" />
              Download PDF
            </Button>
          </div>
        </div>
      </div>

      {/* Report Content */}
      <div className="container max-w-5xl py-8 space-y-12 print:py-0 print:space-y-8">
        {/* Report Header - visible in print */}
        <div className="print:block hidden mb-8">
          <div className="flex items-center gap-3 mb-4">
            <div className="h-8 w-8 rounded bg-neutral-900 flex items-center justify-center">
              <span className="text-white font-bold text-xs">CRV</span>
            </div>
            <span className="font-semibold">Creator Valuation Reports</span>
          </div>
        </div>

        {/* Executive Snapshot */}
        <section className="print-avoid-break">
          <ExecutiveSnapshot report={report} />
        </section>

        <Separator className="my-12 print:my-8" />

        {/* AQV Breakdown */}
        <section className="print-avoid-break">
          <AQVBreakdown report={report} />
        </section>

        <Separator className="my-12 print:my-8" />

        {/* Monetization & Revenue Potential */}
        <section className="print-avoid-break">
          <MonetizationPotential report={report} />
        </section>

        <Separator className="my-12 print:my-8" />

        {/* Peer Benchmarking */}
        <section className="print-avoid-break">
          <PeerBenchmarking report={report} />
        </section>

        <Separator className="my-12 print:my-8" />

        {/* Actionable Recommendations */}
        <section className="print-avoid-break">
          <ActionableRecommendations report={report} />
        </section>

        <Separator className="my-12 print:my-8" />

        {/* Methodology Appendix */}
        <section className="print-break-before">
          <MethodologyAppendix report={report} />
        </section>

        {/* Footer */}
        <footer className="pt-8 border-t text-center print:pt-4">
          <p className="text-xs text-muted-foreground">
            Generated by CRV – Creator Valuation Reports • Confidential
          </p>
        </footer>
      </div>
    </div>
  )
}

